/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator 1.5.0.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/*
 * ApiResponse.h
 *
 * 
 */

#ifndef ApiResponse_H_
#define ApiResponse_H_



undefined
#include <memory>


/// <summary>
/// 
/// </summary>
class  ApiResponse
{
public:
    ApiResponse();
    virtual ~ApiResponse();
    
    std::string toJsonString();
    void fromJsonString(std::string const& jsonString);

    /////////////////////////////////////////////
    /// ApiResponse members
    
    /// <summary>
    /// 
    /// </summary>
    int getCode() const;
    void setCode(int value);
    /// <summary>
    /// 
    /// </summary>
    string getType() const;
    void setType(string value);
    /// <summary>
    /// 
    /// </summary>
    string getMessage() const;
    void setMessage(string value);

protected:
    int m_code;
    string m_Type;
    string m_message;
};


#endif /* ApiResponse_H_ */
