/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator 1.5.0.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "ApiResponse.h"

#include <string>
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;


ApiResponse::ApiResponse()
{
    m_code = ;
    m_Type = ;
    m_message = ;
    }

ApiResponse::~ApiResponse()
{
}

std::string ApiResponse::toJsonString()
{
	std::stringstream ss;
	ptree pt;
	pt.put("code", m_code);
	pt.put("Type", m_Type);
	pt.put("message", m_message);
	write_json(ss, pt, false);
	return ss.str();
}

void ApiResponse::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	m_code = pt.get("code", );
	m_Type = pt.get("Type", );
	m_message = pt.get("message", );
}

int ApiResponse::getCode() const
{
    return m_code;
}
void ApiResponse::setCode(int value)
{
    m_code = value;
}
string ApiResponse::getType() const
{
    return m_Type;
}
void ApiResponse::setType(string value)
{
    m_Type = value;
}
string ApiResponse::getMessage() const
{
    return m_message;
}
void ApiResponse::setMessage(string value)
{
    m_message = value;
}


