/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator 1.5.0.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "Order.h"

#include <string>
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;


Order::Order()
{
    m_id = ;
    m_petId = ;
    m_quantity = ;
    m_shipDate = ;
    m_complete = false;
    }

Order::~Order()
{
}

std::string Order::toJsonString()
{
	std::stringstream ss;
	ptree pt;
	pt.put("id", m_id);
	pt.put("petId", m_petId);
	pt.put("quantity", m_quantity);
	pt.put("shipDate", m_shipDate);
	pt.put("complete", m_complete);
	write_json(ss, pt, false);
	return ss.str();
}

void Order::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	m_id = pt.get("id", );
	m_petId = pt.get("petId", );
	m_quantity = pt.get("quantity", );
	m_shipDate = pt.get("shipDate", );
	m_complete = pt.get("complete", false);
}

int Order::getId() const
{
    return m_id;
}
void Order::setId(int value)
{
    m_id = value;
}
int Order::getPetId() const
{
    return m_petId;
}
void Order::setPetId(int value)
{
    m_petId = value;
}
int Order::getQuantity() const
{
    return m_quantity;
}
void Order::setQuantity(int value)
{
    m_quantity = value;
}
string Order::getShipDate() const
{
    return m_shipDate;
}
void Order::setShipDate(string value)
{
    m_shipDate = value;
}
string Order::getStatus() const
{
    return m_status;
}
void Order::setStatus(string value)
{
    m_status = value;
}
bool Order::getComplete() const
{
    return m_complete;
}
void Order::setComplete(bool value)
{
    m_complete = value;
}


