/**
 * @fileoverview AUTOMATICALLY GENERATED service for IO.OpenAPI.Api.swagger_petstore.
 * Do not edit this file by hand or your changes will be lost next time it is
 * generated.
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 * Version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated at: Mon Jul 02 2018 20:01:49 GMT+1000 (AEST)
 * Generated by: Javascript-Closure-Angular
 */
/**
 * @license Apache 2.0
 * http://www.apache.org/licenses/LICENSE-2.0.html
 */

goog.provide('IO.OpenAPI.Api.swagger_petstore');

goog.require('IO.OpenAPI.Model.Default');
