--[[
  Swagger Petstore
 
  This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 
  OpenAPI spec version: 1.0.0
  Contact: apiteam@swagger.io
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]
-- ApiResponse class
local ApiResponse = {}
local ApiResponse_mt = {
	__name = "ApiResponse";
	__index = ApiResponse;
}

local function cast_ApiResponse(t)
	return setmetatable(t, ApiResponse_mt)
end

local function new_ApiResponse(code, Type, message)
	return cast_ApiResponse({
		["code"] = code;
		["type"] = Type;
		["message"] = message;
	})
end

return {
	cast = cast_ApiResponse;
	new = new_ApiResponse;
}
