--[[
  Swagger Petstore
 
  This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 
  OpenAPI spec version: 1.0.0
  Contact: apiteam@swagger.io
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]
-- Category class
local Category = {}
local Category_mt = {
	__name = "Category";
	__index = Category;
}

local function cast_Category(t)
	return setmetatable(t, Category_mt)
end

local function new_Category(id, name)
	return cast_Category({
		["id"] = id;
		["name"] = name;
	})
end

return {
	cast = cast_Category;
	new = new_Category;
}
