--[[
  Swagger Petstore
 
  This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 
  OpenAPI spec version: 1.0.0
  Contact: apiteam@swagger.io
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]
-- Order class
local Order = {}
local Order_mt = {
	__name = "Order";
	__index = Order;
}

local function cast_Order(t)
	return setmetatable(t, Order_mt)
end

local function new_Order(id, petId, quantity, shipDate, status, complete)
	return cast_Order({
		["id"] = id;
		["petid"] = petId;
		["quantity"] = quantity;
		["shipdate"] = shipDate;
		["status"] = status;
		["complete"] = complete;
	})
end

return {
	cast = cast_Order;
	new = new_Order;
}
