--[[
  Swagger Petstore
 
  This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 
  OpenAPI spec version: 1.0.0
  Contact: apiteam@swagger.io
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]
--[[
Unit tests for openapi.api.petApi
Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
Please update as you see appropriate
]]
describe("petApi", function()
  local openapi_petApi = require "openapi.api.petApi"
  [[-- import all models --]]
  local openapi_Order = require "openapi.model.Order"
  [[-- import all models --]]
  local openapi_Category = require "openapi.model.Category"
  [[-- import all models --]]
  local openapi_User = require "openapi.model.User"
  [[-- import all models --]]
  local openapi_Tag = require "openapi.model.Tag"
  [[-- import all models --]]
  local openapi_Pet = require "openapi.model.Pet"
  [[-- import all models --]]
  local openapi_ApiResponse = require "openapi.model.ApiResponse"
  -- unit tests for addPet
  describe("addPet test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  [[-- import all models --]]
  local openapi_Order = require "openapi.model.Order"
  [[-- import all models --]]
  local openapi_Category = require "openapi.model.Category"
  [[-- import all models --]]
  local openapi_User = require "openapi.model.User"
  [[-- import all models --]]
  local openapi_Tag = require "openapi.model.Tag"
  [[-- import all models --]]
  local openapi_Pet = require "openapi.model.Pet"
  [[-- import all models --]]
  local openapi_ApiResponse = require "openapi.model.ApiResponse"
  -- unit tests for updatePet
  describe("updatePet test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  [[-- import all models --]]
  local openapi_Order = require "openapi.model.Order"
  [[-- import all models --]]
  local openapi_Category = require "openapi.model.Category"
  [[-- import all models --]]
  local openapi_User = require "openapi.model.User"
  [[-- import all models --]]
  local openapi_Tag = require "openapi.model.Tag"
  [[-- import all models --]]
  local openapi_Pet = require "openapi.model.Pet"
  [[-- import all models --]]
  local openapi_ApiResponse = require "openapi.model.ApiResponse"
  -- unit tests for findPetsByStatus
  describe("findPetsByStatus test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  [[-- import all models --]]
  local openapi_Order = require "openapi.model.Order"
  [[-- import all models --]]
  local openapi_Category = require "openapi.model.Category"
  [[-- import all models --]]
  local openapi_User = require "openapi.model.User"
  [[-- import all models --]]
  local openapi_Tag = require "openapi.model.Tag"
  [[-- import all models --]]
  local openapi_Pet = require "openapi.model.Pet"
  [[-- import all models --]]
  local openapi_ApiResponse = require "openapi.model.ApiResponse"
  -- unit tests for findPetsByTags
  describe("findPetsByTags test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  [[-- import all models --]]
  local openapi_Order = require "openapi.model.Order"
  [[-- import all models --]]
  local openapi_Category = require "openapi.model.Category"
  [[-- import all models --]]
  local openapi_User = require "openapi.model.User"
  [[-- import all models --]]
  local openapi_Tag = require "openapi.model.Tag"
  [[-- import all models --]]
  local openapi_Pet = require "openapi.model.Pet"
  [[-- import all models --]]
  local openapi_ApiResponse = require "openapi.model.ApiResponse"
  -- unit tests for getPetById
  describe("getPetById test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  [[-- import all models --]]
  local openapi_Order = require "openapi.model.Order"
  [[-- import all models --]]
  local openapi_Category = require "openapi.model.Category"
  [[-- import all models --]]
  local openapi_User = require "openapi.model.User"
  [[-- import all models --]]
  local openapi_Tag = require "openapi.model.Tag"
  [[-- import all models --]]
  local openapi_Pet = require "openapi.model.Pet"
  [[-- import all models --]]
  local openapi_ApiResponse = require "openapi.model.ApiResponse"
  -- unit tests for updatePetWithForm
  describe("updatePetWithForm test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  [[-- import all models --]]
  local openapi_Order = require "openapi.model.Order"
  [[-- import all models --]]
  local openapi_Category = require "openapi.model.Category"
  [[-- import all models --]]
  local openapi_User = require "openapi.model.User"
  [[-- import all models --]]
  local openapi_Tag = require "openapi.model.Tag"
  [[-- import all models --]]
  local openapi_Pet = require "openapi.model.Pet"
  [[-- import all models --]]
  local openapi_ApiResponse = require "openapi.model.ApiResponse"
  -- unit tests for deletePet
  describe("deletePet test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  [[-- import all models --]]
  local openapi_Order = require "openapi.model.Order"
  [[-- import all models --]]
  local openapi_Category = require "openapi.model.Category"
  [[-- import all models --]]
  local openapi_User = require "openapi.model.User"
  [[-- import all models --]]
  local openapi_Tag = require "openapi.model.Tag"
  [[-- import all models --]]
  local openapi_Pet = require "openapi.model.Pet"
  [[-- import all models --]]
  local openapi_ApiResponse = require "openapi.model.ApiResponse"
  -- unit tests for uploadFile
  describe("uploadFile test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
