--[[
  Swagger Petstore
 
  This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 
  OpenAPI spec version: 1.0.0
  Contact: apiteam@swagger.io
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]
-- Tag class
local Tag = {}
local Tag_mt = {
	__name = "Tag";
	__index = Tag;
}

local function cast_Tag(t)
	return setmetatable(t, Tag_mt)
end

local function new_Tag(id, name)
	return cast_Tag({
		["id"] = id;
		["name"] = name;
	})
end

return {
	cast = cast_Tag;
	new = new_Tag;
}
