--[[
  Swagger Petstore
 
  This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 
  OpenAPI spec version: 1.0.0
  Contact: apiteam@swagger.io
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]
-- User class
local User = {}
local User_mt = {
	__name = "User";
	__index = User;
}

local function cast_User(t)
	return setmetatable(t, User_mt)
end

local function new_User(id, username, firstName, lastName, email, password, phone, userStatus)
	return cast_User({
		["id"] = id;
		["username"] = username;
		["firstname"] = firstName;
		["lastname"] = lastName;
		["email"] = email;
		["password"] = password;
		["phone"] = phone;
		["userstatus"] = userStatus;
	})
end

return {
	cast = cast_User;
	new = new_User;
}
