/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package OpenAPI

type Pet struct {
	id int `json:"id,omitempty"`

	category struct{} `json:"category,omitempty"`

	name string `json:"name"`

	photoUrls [100]string `json:"photourls"`

	tags [100]struct{} `json:"tags,omitempty"`

	// pet status in the store
	status string `json:"status,omitempty"`
}
