/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package OpenAPI

type User struct {
	id int `json:"id,omitempty"`

	username string `json:"username,omitempty"`

	firstName string `json:"firstname,omitempty"`

	lastName string `json:"lastname,omitempty"`

	email string `json:"email,omitempty"`

	password string `json:"password,omitempty"`

	phone string `json:"phone,omitempty"`

	// User Status
	userStatus int `json:"userstatus,omitempty"`
}
