/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.5.0
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.swagger_petstore);
  }
}(this, function(expect, swagger_petstore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new swagger_petstore.Order();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('swagger_petstore', function() {
    it('should create an instance of swagger_petstore', function() {
      // uncomment below and update the code to test swagger_petstore
      //var instance = new swagger_petstore.swagger_petstore();
      //expect(instance).to.be.a(swagger_petstore.swagger_petstore);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new swagger_petstore.Order();
      //expect(instance).to.be();
    });

    it('should have the property petId (base name: "petid")', function() {
      // uncomment below and update the code to test the property petId
      //var instance = new swagger_petstore.Order();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instance = new swagger_petstore.Order();
      //expect(instance).to.be();
    });

    it('should have the property shipDate (base name: "shipdate")', function() {
      // uncomment below and update the code to test the property shipDate
      //var instance = new swagger_petstore.Order();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new swagger_petstore.Order();
      //expect(instance).to.be();
    });

    it('should have the property complete (base name: "complete")', function() {
      // uncomment below and update the code to test the property complete
      //var instance = new swagger_petstore.Order();
      //expect(instance).to.be();
    });

  });

}));
