/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import * as models from './models';

export interface Pet {
    "id"?: number;
    "category"?: object;
    "name": string;
    "photoUrls": Array<string>;
    "tags"?: Array<object>;
    /**
     * pet status in the store
     */
    "status"?: Pet.statusEnum;
}

export namespace Pet {
    export enum statusEnum {
        available = <any> "available",
        pending = <any> "pending",
        sold = <any> "sold"
    }
}
