/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.5.0
 *
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


  /**
   * The Pet model module.
   * @module Pet/Pet
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Pet</code>.
   * @alias module:Pet/Pet
   * @class
   */
  var exports = function() {
    var _this = this;



    _this['name'] = name;
    _this['photourls'] = photoUrls;


  };

  /**
   * Constructs a <code>Pet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Pet/Pet} obj Optional instance to populate.
   * @return {module:Pet/Pet} The populated <code>Pet</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id']
      }
      if (data.hasOwnProperty('category')) {
        obj['category']
      }
      if (data.hasOwnProperty('name')) {
        obj['name']
      }
      if (data.hasOwnProperty('photourls')) {
        obj['photourls']
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags']
      }
      if (data.hasOwnProperty('status')) {
        obj['status']
      }
    }
    return obj;
  }
  /**
   * @member {} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {} category
   */
  exports.prototype['category'] = undefined;
  /**
   * @member {} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {} photourls
   */
  exports.prototype['photourls'] = undefined;
  /**
   * @member {} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * pet status in the store
   * @member {} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @return {}
   */
  exports.prototype.getId = function() {
    return this['id'];
  }

  /**
   * @param {} id
   */
  exports.prototype.setId = function(id) {
    this['id'] = id;
  }

  /**
   * @return {}
   */
  exports.prototype.getCategory = function() {
    return this['category'];
  }

  /**
   * @param {} category
   */
  exports.prototype.setCategory = function(category) {
    this['category'] = category;
  }

  /**
   * @return {}
   */
  exports.prototype.getName = function() {
    return this['name'];
  }

  /**
   * @param {} name
   */
  exports.prototype.setName = function(name) {
    this['name'] = name;
  }

  /**
   * @return {}
   */
  exports.prototype.getPhotoUrls = function() {
    return this['photourls'];
  }

  /**
   * @param {} photoUrls
   */
  exports.prototype.setPhotoUrls = function(photoUrls) {
    this['photourls'] = photoUrls;
  }

  /**
   * @return {}
   */
  exports.prototype.getTags = function() {
    return this['tags'];
  }

  /**
   * @param {} tags
   */
  exports.prototype.setTags = function(tags) {
    this['tags'] = tags;
  }

  /**
   * Returns pet status in the store
   * @return {}
   */
  exports.prototype.getStatus = function() {
    return this['status'];
  }

  /**
   * Sets pet status in the store
   * @param {} status pet status in the store
   */
  exports.prototype.setStatus = function(status) {
    this['status'] = status;
  }


  return exports;
}));
