/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.5.0
 *
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


  /**
   * The User model module.
   * @module User/User
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>User</code>.
   * @alias module:User/User
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:User/User} obj Optional instance to populate.
   * @return {module:User/User} The populated <code>User</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id']
      }
      if (data.hasOwnProperty('username')) {
        obj['username']
      }
      if (data.hasOwnProperty('firstname')) {
        obj['firstname']
      }
      if (data.hasOwnProperty('lastname')) {
        obj['lastname']
      }
      if (data.hasOwnProperty('email')) {
        obj['email']
      }
      if (data.hasOwnProperty('password')) {
        obj['password']
      }
      if (data.hasOwnProperty('phone')) {
        obj['phone']
      }
      if (data.hasOwnProperty('userstatus')) {
        obj['userstatus']
      }
    }
    return obj;
  }
  /**
   * @member {} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {} username
   */
  exports.prototype['username'] = undefined;
  /**
   * @member {} firstname
   */
  exports.prototype['firstname'] = undefined;
  /**
   * @member {} lastname
   */
  exports.prototype['lastname'] = undefined;
  /**
   * @member {} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {} password
   */
  exports.prototype['password'] = undefined;
  /**
   * @member {} phone
   */
  exports.prototype['phone'] = undefined;
  /**
   * User Status
   * @member {} userstatus
   */
  exports.prototype['userstatus'] = undefined;
  /**
   * @return {}
   */
  exports.prototype.getId = function() {
    return this['id'];
  }

  /**
   * @param {} id
   */
  exports.prototype.setId = function(id) {
    this['id'] = id;
  }

  /**
   * @return {}
   */
  exports.prototype.getUsername = function() {
    return this['username'];
  }

  /**
   * @param {} username
   */
  exports.prototype.setUsername = function(username) {
    this['username'] = username;
  }

  /**
   * @return {}
   */
  exports.prototype.getFirstName = function() {
    return this['firstname'];
  }

  /**
   * @param {} firstName
   */
  exports.prototype.setFirstName = function(firstName) {
    this['firstname'] = firstName;
  }

  /**
   * @return {}
   */
  exports.prototype.getLastName = function() {
    return this['lastname'];
  }

  /**
   * @param {} lastName
   */
  exports.prototype.setLastName = function(lastName) {
    this['lastname'] = lastName;
  }

  /**
   * @return {}
   */
  exports.prototype.getEmail = function() {
    return this['email'];
  }

  /**
   * @param {} email
   */
  exports.prototype.setEmail = function(email) {
    this['email'] = email;
  }

  /**
   * @return {}
   */
  exports.prototype.getPassword = function() {
    return this['password'];
  }

  /**
   * @param {} password
   */
  exports.prototype.setPassword = function(password) {
    this['password'] = password;
  }

  /**
   * @return {}
   */
  exports.prototype.getPhone = function() {
    return this['phone'];
  }

  /**
   * @param {} phone
   */
  exports.prototype.setPhone = function(phone) {
    this['phone'] = phone;
  }

  /**
   * Returns User Status
   * @return {}
   */
  exports.prototype.getUserStatus = function() {
    return this['userstatus'];
  }

  /**
   * Sets User Status
   * @param {} userStatus User Status
   */
  exports.prototype.setUserStatus = function(userStatus) {
    this['userstatus'] = userStatus;
  }


  return exports;
}));
